In [1]:
import tensorflow as tf
import numpy as np

2023-03-06 21:31:10.432450: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
X = []
Y = []
for i in range(6):
    lst = list(range(i, i+4))

    X.append(list(map(lambda c: [c/10], lst)))
    Y.append((i+4)/10)

X = np.array(X)
Y = np.array(Y)


In [8]:
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=10, return_sequences=False, input_shape=[4,1]),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer = 'adam', loss='mse')
model.summary()

2023-03-06 21:36:01.673806: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 10)                120       
                                                                 
 dense (Dense)               (None, 1)                 11        
                                                                 
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.fit(X, Y, epochs=100, verbose=0)

In [12]:
model.predict(np.array([[[0.6], [0.7], [0.8], [0.9]]]))

1/1 [==============================] - 1s 900ms/step


array([[0.9154298]], dtype=float32)

In [13]:
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=10, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.SimpleRNN(units=10, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.SimpleRNN(units=10, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.SimpleRNN(units=10, return_sequences=False, input_shape=[4,1]),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer = 'adam', loss='mse')
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 4, 10)             120       
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 4, 10)             210       
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, 4, 10)             210       
                                                                 
 simple_rnn_4 (SimpleRNN)    (None, 10)                210       
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 761
Trainable params: 761
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.fit(X, Y, epochs=100, verbose=0)

In [15]:
model.predict(np.array([[[0.6], [0.7], [0.8], [0.9]]]))

1/1 [==============================] - 1s 643ms/step


array([[0.91955835]], dtype=float32)

## LSTM

In [17]:
X = []
Y = []
for i in range(3000):
    lst = np.random.rand(100)
    idx = np.random.choice(100, 2, replace=False)
    zeros = np.zeros(100)
    zeros[idx] = 1
    X.append(np.array(list(zip(zeros,lst))))
    Y.append(np.prod(lst[idx]))

print(X[0], Y[0])

[[0.         0.79664655]
 [0.         0.88735637]
 [0.         0.30276085]
 [0.         0.3329574 ]
 [0.         0.20408078]
 [0.         0.12985826]
 [0.         0.92771967]
 [1.         0.85466793]
 [0.         0.4072755 ]
 [0.         0.73875575]
 [0.         0.23577355]
 [0.         0.78248381]
 [0.         0.51616819]
 [0.         0.01394269]
 [0.         0.61889164]
 [0.         0.64901141]
 [0.         0.1923458 ]
 [0.         0.81740062]
 [0.         0.33182417]
 [0.         0.40574117]
 [0.         0.66921988]
 [0.         0.4278286 ]
 [0.         0.64447494]
 [0.         0.42278437]
 [0.         0.73727395]
 [0.         0.42018455]
 [0.         0.27322182]
 [0.         0.48537113]
 [0.         0.44271942]
 [0.         0.98480916]
 [0.         0.53585025]
 [0.         0.35317187]
 [0.         0.17981118]
 [0.         0.59603238]
 [0.         0.5345138 ]
 [0.         0.55863505]
 [0.         0.92138532]
 [0.         0.81508885]
 [0.         0.93115672]
 [0.         0.64337036]


In [18]:
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units = 30, return_sequences=True, input_shape = [100,2]),
    tf.keras.layers.SimpleRNN(units = 30),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_5 (SimpleRNN)    (None, 100, 30)           990       
                                                                 
 simple_rnn_6 (SimpleRNN)    (None, 30)                1830      
                                                                 
 dense_2 (Dense)             (None, 1)                 31        
                                                                 
Total params: 2,851
Trainable params: 2,851
Non-trainable params: 0
_________________________________________________________________


In [19]:
X = np.array(X)
Y = np.array(Y)

history = model.fit(X[:2560], Y[:2560], epochs=100, validation_split=0.2)

Epoch 1/100
64/64 [==============================] - 5s 38ms/step - loss: 0.0720 - val_loss: 0.0422
Epoch 2/100
64/64 [==============================] - 3s 50ms/step - loss: 0.0517 - val_loss: 0.0533
Epoch 3/100
64/64 [==============================] - 4s 66ms/step - loss: 0.0513 - val_loss: 0.0407
Epoch 4/100
64/64 [==============================] - 4s 65ms/step - loss: 0.0504 - val_loss: 0.0430
Epoch 5/100
64/64 [==============================] - 4s 70ms/step - loss: 0.0508 - val_loss: 0.0453
Epoch 6/100
64/64 [==============================] - 4s 59ms/step - loss: 0.0507 - val_loss: 0.0519
Epoch 7/100
64/64 [==============================] - 4s 64ms/step - loss: 0.0511 - val_loss: 0.0440
Epoch 8/100
64/64 [==============================] - 4s 68ms/step - loss: 0.0509 - val_loss: 0.0430
Epoch 9/100
64/64 [==============================] - 4s 56ms/step - loss: 0.0502 - val_loss: 0.0409
Epoch 10/100
64/64 [==============================] - 4s 63ms/step - loss: 0.0505 - val_loss: 0.0416

In [22]:
path_train_text = '/Users/seokholee/lsh/study/DL/nsmc-master/nsmc-master/ratings_train.txt'
path_test_text = '/Users/seokholee/lsh/study/DL/nsmc-master/nsmc-master/ratings_test.txt'

In [24]:
train_text = open(path_train_text, 'rb').read().decode(encoding='utf-8')
test_text = open(path_test_text, 'rb').read().decode(encoding='utf-8')

In [25]:
train_Y = np.array([[int(row.split('\t')[2])] for row in train_text.split('\n')[1:] if row.count('\t')>0])
test_Y = np.array([[int(row.split('\t')[2])] for row in test_text.split('\n')[1:] if row.count('\t')>0])

In [29]:
import numpy as np
import pandas as pd

x = [np.nan,1,2,3,4,5]
y = pd.Series([x[np.random.randint(0,6)] for i in range(20)])

In [33]:
y.isna().sum()

5

In [37]:
y.fillna(y[~y.isna()].mean())

0     3.0
1     2.0
2     3.0
3     3.0
4     4.0
5     4.0
6     4.0
7     4.0
8     3.0
9     1.0
10    3.0
11    1.0
12    3.0
13    3.0
14    3.0
15    4.0
16    2.0
17    3.0
18    3.0
19    4.0
dtype: float64